module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/JqGh3LtWerw35NILvYQlFb',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/oekb4n.jpg',
    NEWSLETTER_JID: '120363400717651069@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '⟆⟆ 𝙉𝙊𝙑𝘼 𝘿𝙀𝙑𝙎 𝙈𝘿 ⟅⟅',
    OWNER_NAME: '𝙉𝙊𝙑𝘼 𝘿𝙀𝙑𝙎',
    OWNER_NUMBER: '2348157763037',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © ᴘᴏᴡᴇʀᴇᴅ ʙʏ ɴᴏᴠᴀ ᴅᴇᴠꜱ-ᴍᴅ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbArJKqJf05kN32opJ2l'
};
